INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10001, 'USD', 'INR', 65.00, 'dev');
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10002, 'EUR', 'INR', 75.00, 'dev');
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10003, 'AUD', 'INR', 55.00, 'dev');
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10004, 'USD', 'EUR', 75.00, 'dev');
INSERT INTO CURRENCY_EXCHANGE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENVIRONMENT) VALUES (10005, 'USD', 'GBP', 65.00, 'dev');
